# Ex1 - Filtering and Sorting Data

Check out [Chipotle Exercises Video Tutorial](https://youtu.be/ZZPiWZpdekA) to watch a data scientist go through the exercises

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep = '\t')

### Step 4. How many products cost more than $10.00?

In [3]:
# the item price column is actullay the price of the product multiplied by the quantity
chipo.loc[(chipo["choice_description"] == '[Diet Coke]') & (chipo["item_name"] == "Canned Soda")]

      order_id  quantity    item_name choice_description item_price
162         73         2  Canned Soda        [Diet Coke]     $2.18
200         89         1  Canned Soda        [Diet Coke]     $1.09
317        138         1  Canned Soda        [Diet Coke]     $1.09
350        150         2  Canned Soda        [Diet Coke]     $2.18
370        160         1  Canned Soda        [Diet Coke]     $1.09
779        321         1  Canned Soda        [Diet Coke]     $1.09
1216       496         1  Canned Soda        [Diet Coke]     $1.09
1662       672         1  Canned Soda        [Diet Coke]     $1.09
1953       790         1  Canned Soda        [Diet Coke]     $1.09
2135       859         2  Canned Soda        [Diet Coke]     $2.18
2544      1009         1  Canned Soda        [Diet Coke]     $1.09
2850      1132         1  Canned Soda        [Diet Coke]     $1.09
3592      1440         2  Canned Soda        [Diet Coke]     $2.18
3793      1518         1  Canned Soda        [Diet Coke]     $1.09
4008      1604         1  Canned Soda        [Diet Coke]     $1.09

In [ ]:
# adding a new column representing the price of each single product in float
chipo["item_price"] = chipo["item_price"].str.replace("$", "", regex=False).astype(float)
chipo["product_price"] = chipo["item_price"] / chipo["quantity"]
chipo

,order_id,quantity,item_name,choice_description,item_price,product_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [5]:
#checking everything is correct
chipo.loc[(chipo["choice_description"] == '[Diet Coke]') & (chipo["item_name"] == "Canned Soda")]

,order_id,quantity,item_name,choice_description,item_price,product_price
162,73,2,Canned Soda,[Diet Coke],2.18,1.09
200,89,1,Canned Soda,[Diet Coke],1.09,1.09
317,138,1,Canned Soda,[Diet Coke],1.09,1.09
350,150,2,Canned Soda,[Diet Coke],2.18,1.09
370,160,1,Canned Soda,[Diet Coke],1.09,1.09
779,321,1,Canned Soda,[Diet Coke],1.09,1.09
1216,496,1,Canned Soda,[Diet Coke],1.09,1.09
1662,672,1,Canned Soda,[Diet Coke],1.09,1.09
1953,790,1,Canned Soda,[Diet Coke],1.09,1.09
2135,859,2,Canned Soda,[Diet Coke],2.18,1.09
2544,1009,1,Canned Soda,[Diet Coke],1.09,1.09
2850,1132,1,Canned Soda,[Diet Coke],1.09,1.09
3592,1440,2,Canned Soda,[Diet Coke],2.18,1.09
3793,1518,1,Canned Soda,[Diet Coke],1.09,1.09
4008,1604,1,Canned Soda,[Diet Coke],1.09,1.09

In [ ]:
# removing duplicated products
filtered_chipo=chipo.drop_duplicates(['item_name','choice_description'])

In [ ]:
# filtering products that costs more than $10
filtered_chipo = filtered_chipo.loc[ filtered_chipo["product_price"]>10.0 , ["item_name","choice_description","product_price"] ].reset_index(drop=True)

In [8]:
print(f"the number of products that cost more than $10.00 is {filtered_chipo.shape[0]}")

the number of products that cost more than $10.00 is 707

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [11]:
filtered_chipo[["item_name","choice_description","product_price"]]

,item_name,choice_description,product_price
0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
4,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
702,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
703,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
704,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
705,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
706,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

### Step 6. Sort by the name of the item

In [25]:
chipo.item_name.sort_values()

# OR

chipo.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
4084,1635,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [14]:
chipo.loc[chipo["item_price"].idxmax()]["quantity"]

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [15]:
chipo[chipo["item_name"]=="Veggie Salad Bowl"]["quantity"].sum()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [16]:
chipo[ ( chipo["item_name"]=="Canned Soda" ) & ( chipo["quantity"]>1 )].shape[0]

20